# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ErrorListChecker
                                 A QGIS plugin
 Error List Checker
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-21
        copyright            : (C) 2024 by PSA
        email                : test@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import pathlib
import sys


src_dir = pathlib.Path(__file__).parent.resolve()

pyspellchecker_whl = src_dir / "pyspellchecker.whl"
if pyspellchecker_whl.exists():
    sys.path.append(str(pyspellchecker_whl))


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ErrorListChecker class from file ErrorListChecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .error_list_checker import ErrorListChecker
    return ErrorListChecker(iface)
